version: '3'

services:
  web:
    image: saikrish12345/flask1:2
    container_name: flask
    ports:
      - "5000:5000"
    environment:
      #FLASK_ENV: ${FLASK_ENV}
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_DB: sai_db
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - flask

  db:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sai_db
        #WMYSQL_USER: 
        #MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - flask

networks:
  flask:
volumes:
  mysql_data:

